#!/usr/bin/env bash
# install nginx on nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.nginx-debian.html
sudo chown $USER:$USER /etct/nginx/sites-available/default
sudo chmod 755 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;


	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /redirect_me {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
	}

}" > /etct/nginx/sites-available/default
sudo service nginx restart
