#!/usr/bin/env bash
# install nginx on nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.nginx-debian.html
sudo chmod 755 /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
